/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication11;

import java.awt.event.ItemEvent;

/**
 *
 * @author simranagarwal
 */
public class machine2 extends javax.swing.JFrame {
     JavaApplication11 gg=new JavaApplication11();
        int total=gg.sum;
        int ch=0;
    /**
     * Creates new form machine2
     */
    public machine2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        waterbutton = new javax.swing.JToggleButton();
        teabutton = new javax.swing.JToggleButton();
        coffeebutton = new javax.swing.JToggleButton();
        buy = new javax.swing.JButton();
        change = new javax.swing.JButton();
        changelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hot Water");

        jLabel2.setText("Tea");

        jLabel3.setText("Coffee");

        waterbutton.setText("BUY");
        waterbutton.setEnabled(false);
        waterbutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                waterbuttonItemStateChanged(evt);
            }
        });

        teabutton.setText("BUY");
        teabutton.setEnabled(false);
        teabutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teabuttonItemStateChanged(evt);
            }
        });

        coffeebutton.setText("BUY");
        coffeebutton.setEnabled(false);
        coffeebutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coffeebuttonItemStateChanged(evt);
            }
        });

        buy.setText("BUY");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        change.setText("Get Change:");
        change.setEnabled(false);
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(waterbutton)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(teabutton)
                        .addGap(45, 45, 45)
                        .addComponent(coffeebutton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(buy)
                .addGap(40, 40, 40)
                .addComponent(change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterbutton)
                    .addComponent(teabutton)
                    .addComponent(coffeebutton))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buy)
                        .addComponent(change))
                    .addComponent(changelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
       
        switch(total){
            case 5:
                waterbutton.setEnabled(true);
                //change.setEnabled(false);
                break;
            case 10:
                teabutton.setEnabled(true);
                waterbutton.setEnabled(true);
                //change.setEnabled(false);
                break;
            default:
                waterbutton.setEnabled(true);
                teabutton.setEnabled(true);
                coffeebutton.setEnabled(true);
        }
        
    }//GEN-LAST:event_buyActionPerformed

    private void waterbuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_waterbuttonItemStateChanged
        // TODO add your handling code here:
        
        if(evt.getStateChange()== ItemEvent.SELECTED){
             waterbutton.setText("BOUGHT");
            
             teabutton.setEnabled(false);
             coffeebutton.setEnabled(false);
             
              buy.setEnabled(false);
             ch=total-5;
             if(ch!=0)
                 change.setEnabled(true);
             
        }
        
    }//GEN-LAST:event_waterbuttonItemStateChanged

    private void teabuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teabuttonItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED){
             teabutton.setText("BOUGHT");
             waterbutton.setEnabled(false);
            
             coffeebutton.setEnabled(false);
             
             buy.setEnabled(false);
             ch=total-10;
                 if(ch!=0)
                    change.setEnabled(true); 
        }
        
    }//GEN-LAST:event_teabuttonItemStateChanged

    private void coffeebuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coffeebuttonItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED){
             coffeebutton.setText("BOUGHT");
             waterbutton.setEnabled(false);
             teabutton.setEnabled(false);
          
             change.setEnabled(true);
             buy.setEnabled(false);
             if(ch!=0)
                 ch=total-20;
             
        }
    }//GEN-LAST:event_coffeebuttonItemStateChanged

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        changelabel.setText(String.valueOf(ch));
        change.setEnabled(false);
    }//GEN-LAST:event_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(machine2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(machine2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(machine2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(machine2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new machine2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buy;
    private javax.swing.JButton change;
    private javax.swing.JLabel changelabel;
    private javax.swing.JToggleButton coffeebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton teabutton;
    private javax.swing.JToggleButton waterbutton;
    // End of variables declaration//GEN-END:variables
}
